language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t eduardofortes/docker-react -f Dockerfile.dev .

script:
  - docker run eduardofortes/docker-react npm run test -- --coverage